version: '3.8'

services:
  # Service Apache với PHP
  apache:
    build:
      context: . 
      dockerfile: 1_apache/Dockerfile  
    container_name: my-apache
    restart: always
    volumes:
      - ./laravel-app:/usr/local/apache2/htdocs
    ports:
      - "8088:80"
    networks:
      - app-network

  # Container PHP-FPM
  php-fpm:
    build:
      context: . 
      dockerfile: 2_php/Dockerfile
    container_name: php-fpm-container
    volumes:
      - ./laravel-app:/var/www/html
    #environment:
    #  - DB_CONNECTION=mysql # ten service 
    #  - DB_HOST=mysql  
    #  - DB_PORT=3306
    #  - DB_DATABASE=my_database
    #  - DB_USERNAME=user
    #  - DB_PASSWORD=userpassword
    networks:
      - app-network
  
  # Container Composer
  composer:
    image: composer:latest
    container_name: composer-container
    volumes:
      - ./laravel-app:/app
    working_dir: /app
    command: tail -f /dev/null
    networks:
      - app-network
    restart: always

  # Service MySQL----------------------DB của ứng dụng#
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    restart: always

  # Service phpMyAdmin--------------------- giao diện cho mysql#
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: mysql  # Địa chỉ host của MySQL (dùng tên service MySQL trong Docker Compose)
      PMA_PORT: 3306    # Cổng MySQL
      PMA_USER: user
      PMA_PASSWORD: userpassword
    ports:
      - "8089:80"  # Truy cập phpMyAdmin qua cổng 8089
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
